osx_image: xcode7.3

sudo: required
dist: trusty

language: node_js
node_js: "8"

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

os:
  - linux
  - osx

cache:
  directories:
    #- node_modules
    - "$HOME/.electron"
    - "$HOME/.cache"

before_install:
  - sudo apt update
  - sudo apt install --yes snapd

install:
  - mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v2.2.1/git-lfs-$([ "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-2.2.1.tar.gz | tar -xz -C /tmp/git-lfs --strip-components 1 && /tmp/git-lfs/git-lfs pull
  - curl -L https://github.com/yarnpkg/yarn/releases/download/v1.0.1/yarn-v1.0.1.tar.gz | tar xvz && mv yarn-v1.0.1 $HOME/.yarn
  - export PATH="$HOME/.yarn/bin:$PATH"
  - sudo snap install snapcraft --classic --edge
  - npm install -g gulp-cli
  - yarn

# before_script:
#   - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; sleep 3; fi

script:
  - yarn write_audiosearch_creds_to_file
  - gulp
#  - yarn test && yarn dist
  - yarn dist

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"

notifications:
  email:
    on_success: always # default: change
    on_failure: always # default: always
